variable "container_runtime" {} //docker or containerd (defined in main.tf in root module)

variable "default_folder_id" { //your default folder-id
  default = "<your-folder-id>" 
}

variable "default_cloud_id" {  //your default cloud-id
  default = "<your-cloud-id>" 
}

variable "default_token" { //your token that should be generated by 'yc iam create-token'
  type    = string 
  default = "<your-token>"
}

variable "default_zone" {} //your default zone (defined in main.tf in root module)


variable "default_network_id" { //your network-id 
  default = "<your-network-id>"
}

variable "default_subnet_id" { //your subnet-id
  default = "<your-subnet-id>"
}

variable "version_of_k8s_cluster" {} //version of your cluster and your node-group


variable "default_sa_id" { //your default service-account-id
  default = "<your-service-account-id>"
}

variable "default_node_sa_id" { //your default node-service-account-id
  default = "<your-node-service-account-id>"
}

variable "release_channel" {} //your release channel: RAPID, REGULAR or STABLE (defined in main.tf in root module)

variable "default_type" {
  default = "network-hdd" // network-hdd, network-ssd, network-ssd-nonreplicated
}

variable "default_size" {
  default = "size_hdd_or_ssd" // size_hdd_or_ssd or size_nrd. If you use network-hdd or network-ssd, your option is 'size_hdd_or_ssd'; if you use NRD, your option is 'size_nrd'
}

variable "default_platform_id" {} //your default platform-id (defined in main.tf in root module)


variable "default_memory" {
  default = "memory_with_no_gpu" // "memory_with_gpu" or "memory_with_no_gpu". If you use gpus, your option is "memory_with_gpu"; if you don't use gpus, your option is "memory_with_no_gpu"
}

variable "default_cores" {
  default = "cores_with_no_gpu" // "cores_with_gpu" or "cores_with_no_gpu". If you use gpus, your option is "cores_with_gpu"; if you don't use gpus, your option is "cores_with_no_gpu"
}

variable "environment" {
  default = "prod"  // "prod" or "test". The 'core_fraction'=100%, if you use "prod"; the 'core_fraction'=50%, if you use "test"
}

variable "default_gpu" {
  default = "no_gpu" // "gpu" or "no_gpu". If you use gpus, your option is "gpu"; if you don't use gpus, your option is "no_gpu"
}


variable "default_having_size" { //if you use network-hdd or network-ssd, the size will be 64Gb; if you use NRD, the size will be 93 Gb
  default = {
    "size_hdd_or_ssd" = 64
    "size_nrd" = 93
  }
}

variable "default_having_memory" { //if you use gpu, the memory will be 119 Gb; if you don't use gpu, the memory will be 2 Gb
  default = {
    "memory_with_gpu" = 119
    "memory_with_no_gpu" = 2
  }
}

variable "default_having_cores" { //if you use gpu, the number of cores will be 28; if you don't use gpu, the number of cores will be 2
  default = {
    "cores_with_gpu" = 28
    "cores_with_no_gpu" = 2
  }
}

variable "default_having_core_fraction" { //if you need the cluster for production, cores_fraction parameter will be 100%; if you need the cluster for testing purposes, cores_fraction parameter will be 50%
  default = {
    "prod" = 100
    "test" = 50
    //"dev" = 20
  }
}

variable "default_having_gpu" { //if you use gpu, the number of gpus will be 1; if you don't use gpu, the number of gpus will be 0
  default = {
    "gpu" = 1
    "no_gpu" = 0
  }
}
